### PR TITLE
Add Class Notes Tab

### PR DESCRIPTION
**Pull request by DhruvaSambrani**
I've added a Class notes tab. Please do merge if you are ok with it

### CODE REVIEW

**Comment by sejdm** [comment]
> I've added a Class notes tab. Please do merge if you are ok with it

 The actual source for this website is hosted on this repository: https://github.com/sejdm/idc204source .  A static site generator program (written using the [Hakyll module](https://jaspervdj.be/hakyll/) in Haskell) converts that into the the HTML/CSS code for this website. Therefore, with the next update, your changes will be overwritten and any changes to the website are meant to be made in the source.

Are you planning to host the class notes files somewhere else and fetch them on this page dynamically? If you plan to maintain class notes regularly, then I can add a directory for it in the source and modify the program to automatically compile and add links to files in it  and generate pdf versions. You can send the file via email or host it somewhere so that I can modify the Makefile to also fetch the files while compiling.

**Comment by DhruvaSambrani** [comment]
Oh okay.
I was thinking of hosting it in the repo itself. But anywhere else also is fine

**Comment by DhruvaSambrani** [comment]
Let me know what would be convenient

**Comment by sejdm** [comment]
Are you typesetting your lecture notes in LaTeX or something? In that case, I have added support for lecture notes.  In case you want to share your lecture notes on the website, you could give me the source file written in markdown which is the very lightweight markup language used to markup this very git comment and/ README.md. It also recognizes LaTeX code when flanked by the usual dollar symbol. As an example, you can see [this raw file](https://raw.githubusercontent.com/sejdm/idc204source/master/posts/2020-01-15-operator-precedence.md) that created the post on boolean operator precedence.

**Comment by DhruvaSambrani** [comment]
I'll be writing in md. I've converted to pdf using pandoc, but can share the md file itself. Where do i add them? Directly uploading may be easier than sending it to you and then you upload, but I can do both

**Comment by sejdm** [comment]
Thanks a lot for doing this! 

Sharing the .md file is better because then an HTML version will also be created. Indeed, the program also uses pandoc (which is also written in Haskell as is Hakyll) in the background for conversions.

One possibility would be to use a pull request. Add the file to the "lecturenotes" folder in [the source repository](https://github.com/sejdm/idc204source). It will be compiled and linked in the appropriate places when I trigger the update. Even then, I will anyway have to merge the commit with the rest, so even just mailing me the markdown file should be fine if that proves more convenient for you.

**Comment by DhruvaSambrani** [comment]
Ok, will email. Which id?

**Comment by sejdm** [comment]
> Ok, will email. Which id?

`shane`

**Comment by DhruvaSambrani** [comment]
Thanks, will do. Closing this Merge.

**Comment by sejdm** [comment]
Sure, thanks!!

**Pull request closed without merging**
